In [46]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.preprocessing import LabelEncoder  

sep = ':::'

In [70]:
train_data = pd.read_csv('/Users/deepakshivajiharak/Desktop/Internship/Movie Genre/train_data.txt', sep=':::', engine='python', header=None, names=['ID', 'TITLE', 'GENRE', 'DESCRIPTION'])
test_data = pd.read_csv('/Users/deepakshivajiharak/Desktop/Internship/Movie Genre/test_data.txt', sep=':::', engine='python',header=None, names=['ID', 'TITLE', 'GENRE', 'DESCRIPTION'])
test_data_solution = pd.read_csv('/Users/deepakshivajiharak/Desktop/Internship/Movie Genre/test_data_solution.txt', sep=':::', engine='python', header=None, names=['ID', 'TITLE', 'GENRE', 'DESCRIPTION'])

In [71]:
print("train data columns and sample:")
train_data.columns
train_data.head()

train data columns and sample:

,ID,TITLE,GENRE,DESCRIPTION
0,1,Oscar et la dame rose (2009),drama,Listening in to a conversation between his do...
1,2,Cupid (1997),thriller,A brother and sister with a past incestuous r...
2,3,"Young, Wild and Wonderful (1980)",adult,As the bus empties the students for their fie...
3,4,The Secret Sin (1915),drama,To help their unemployed father make ends mee...
4,5,The Unrecovered (2007),drama,The film's title refers not only to the un-re...

In [72]:
print("\nTest data columns and sample:")
test_data.columns
test_data.head()

Test data columns and sample:

,ID,TITLE,GENRE,DESCRIPTION
0,1,Edgar's Lunch (1998),"L.R. Brane loves his life - his car, his apar...",NaN
1,2,La guerra de papá (1977),"Spain, March 1964: Quico is a very naughty ch...",NaN
2,3,Off the Beaten Track (2010),One year in the life of Albin and his family ...,NaN
3,4,Meu Amigo Hindu (2015),"His father has died, he hasn't spoken with hi...",NaN
4,5,Er nu zhai (1955),Before he was known internationally as a mart...,NaN

In [73]:
print("\nTest data solution columns and sample")
test_data_solution.columns
test_data_solution.head()

Test data solution columns and sample

,ID,TITLE,GENRE,DESCRIPTION
0,1,Edgar's Lunch (1998),thriller,"L.R. Brane loves his life - his car, his apar..."
1,2,La guerra de papá (1977),comedy,"Spain, March 1964: Quico is a very naughty ch..."
2,3,Off the Beaten Track (2010),documentary,One year in the life of Albin and his family ...
3,4,Meu Amigo Hindu (2015),drama,"His father has died, he hasn't spoken with hi..."
4,5,Er nu zhai (1955),drama,Before he was known internationally as a mart...

In [76]:
plot_column = 'DESCRIPTION'
genre_column = 'GENRE'

train_data[plot_column].fillna('', inplace=True)
test_data[plot_column].fillna('', inplace=True)

label_encoder = LabelEncoder()
train_data['genre_encoded'] = label_encoder.fit_transform(train_data[genre_column])

tfidf_vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
X_train_tfidf = tfidf_vectorizer.fit_transform(train_data[plot_column])
X_test_tfidf = tfidf_vectorizer.transform(test_data[plot_column])

X = X_train_tfidf
y = train_data['genre_encoded']

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [79]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

log_reg = LogisticRegression(max_iter=1000)
log_reg.fit(X_train, y_train)

y_val_pred = log_reg.predict(X_val)

print("Logistic Regression")
print("Accurecy:", accuracy_score(y_val, y_val_pred))
print(classification_report(y_val, y_val_pred, target_names=label_encoder.classes_))

Logistic Regression
Accurecy: 0.5794521811306834
               precision    recall  f1-score   support

      action        0.52      0.26      0.34       263
       adult        0.73      0.21      0.33       112
   adventure        0.43      0.14      0.22       139
   animation        0.62      0.10      0.17       104
   biography        0.00      0.00      0.00        61
      comedy        0.51      0.58      0.55      1443
       crime        0.29      0.02      0.04       107
 documentary        0.66      0.84      0.74      2659
       drama        0.54      0.78      0.64      2697
      family        0.39      0.07      0.12       150
     fantasy        0.00      0.00      0.00        74
   game-show        0.94      0.42      0.59        40
     history        0.00      0.00      0.00        45
      horror        0.64      0.56      0.60       431
       music        0.62      0.47      0.54       144
     musical        1.00      0.02      0.04        50
     mystery        0.00      0.00      0.00        56
        news        1.00      0.06      0.11        34
  reality-tv        0.47      0.18      0.26       192
     romance        0.17      0.01      0.01       151
      sci-fi        0.57      0.22      0.31       143
       short        0.47      0.33      0.39      1045
       sport        0.58      0.19      0.29        93
   talk-show        0.65      0.14      0.22        81
    thriller        0.38      0.14      0.21       309
         war        0.00      0.00      0.00        20
     western        0.95      0.70      0.80       200

     accuracy                           0.58     10843
    macro avg       0.49      0.24      0.28     10843
 weighted avg       0.55      0.58      0.54     10843

/opt/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [80]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_train, y_train)

y_val_pred = nb.predict(X_val)

print("Naive bayes")
print("Accuracy:", accuracy_score(y_val, y_val_pred))
print(classification_report(y_val, y_val_pred, target_names=label_encoder.classes_))

Naive bayes
Accuracy: 0.52310246241815
               precision    recall  f1-score   support

      action        0.57      0.08      0.14       263
       adult        0.88      0.06      0.12       112
   adventure        0.29      0.03      0.05       139
   animation        0.00      0.00      0.00       104
   biography        0.00      0.00      0.00        61
      comedy        0.51      0.44      0.47      1443
       crime        0.00      0.00      0.00       107
 documentary        0.58      0.88      0.70      2659
       drama        0.46      0.83      0.59      2697
      family        1.00      0.01      0.01       150
     fantasy        0.00      0.00      0.00        74
   game-show        1.00      0.15      0.26        40
     history        0.00      0.00      0.00        45
      horror        0.73      0.38      0.50       431
       music        0.79      0.10      0.18       144
     musical        0.00      0.00      0.00        50
     mystery        0.00      0.00      0.00        56
        news        0.00      0.00      0.00        34
  reality-tv        0.80      0.02      0.04       192
     romance        0.00      0.00      0.00       151
      sci-fi        0.86      0.04      0.08       143
       short        0.59      0.11      0.18      1045
       sport        0.73      0.09      0.15        93
   talk-show        0.00      0.00      0.00        81
    thriller        0.27      0.01      0.02       309
         war        0.00      0.00      0.00        20
     western        0.98      0.59      0.74       200

     accuracy                           0.52     10843
    macro avg       0.41      0.14      0.16     10843
 weighted avg       0.52      0.52      0.44     10843

/opt/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))